- name: e2e tests
  uses: cypress-io/github-action@v5
  with:
    command: npm run test:e2e
    start: npm run start-prod
    wait-on: http://localhost:5000

jobs:
  pokedex_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Run tests
        run: |
          npm run test:e2e